/**
 * SERVICIOS QUINTANA LLC - PREMIUM GLOBAL JS
 * Features: i18n, Scroll Reveal, Custom Cursor, Micro-Interactions
 */

const translations = {
    en: {
        nav_divisions: "Our Brands",
        nav_about: "About",
        nav_contact: "Contact HQ",
        hero_eyebrow: "Est. 2026 • Colorado",
        hero_h1: "Bridging the Gap Between Community & Compliance.",
        hero_sub: "Servicios Quintana LLC is Colorado's home for trusted, bilingual services that make official, government, and digital processes accessible to everyone. We bring together three specialized brands under one mission: helping our community navigate paperwork, agencies, and technology with clarity and confidence.",
        btn_view_companies: "View Our Brands",
        div_header: "Our Brands",
        div_sub: "We operate three distinct brands serving the Denver Metro area.",
        badge_auth: "Document Authentication",
        badge_admin: "Administrative Support",
        badge_digital: "Digital Strategy & Web Development",
        badge_translation: "Translation Services",
        card_notary_title: "Quintana Notary & Signing",
        card_notary_text: "Mobile, bilingual notary services for real estate closings, affidavits, power of attorney, and more. We bring the office to your doorstep.",
        card_dmv_title: "Ayuda DMV",
        card_dmv_text: "Specialized assistance for Spanish‑speaking residents navigating Colorado DMV requirements. We simplify state processes so families can move forward without stress.",
        card_dev_title: "David Quintana Dev",
        card_dev_text: "High‑performance, bilingual web architecture for local businesses. We build accessible, modern websites with custom coding and community‑focused design.",
        card_translation_title: "Certified Translation Services",
        card_translation_text: "Professional certified translations for families, students, and individuals completing immigration, academic, or government paperwork. Every translation includes a signed Declaration of Accuracy designed to meet the strict submission requirements of USCIS, the Colorado DMV, schools, and state agencies.",
        card_translation_contact: "Learn More About Translation Services",
        card_visit: "Visit Official Site",
        card_portfolio: "Visit Portfolio Site",
        about_h2: "Built on Integrity",
        about_p1: "Servicios Quintana LLC brings together the professional work of David Quintana.",
        about_p2: "Whether we are notarizing a loan document in Castle Rock, helping a family register a vehicle, or writing semantic HTML for a local business, our core value remains the same: Accessibility.",
        about_p3: "Language barriers and technical complexity should never prevent someone from achieving their goals.",
        about_trust_h3: "Why Colorado Trusts Us",
        stat_brands: "Active Brands",
        stat_bilingual: "Bilingual",
        stat_local: "Locally Owned",
        footer_brand_tagline: "Reliable. Mobile. Bilingual.",
        footer_hq: "Corporate HQ & Registered Agent",
        footer_contact_title: "Contact",
        footer_statutory_en: "Important Notice: Servicios Quintana LLC and its representatives are not attorneys licensed to practice law in the State of Colorado. We may not give legal advice or accept fees for legal advice. We provide administrative, translation, and notary public services only.",
        footer_statutory_es: "Aviso Importante: Servicios Quintana LLC y sus representantes no son abogados licenciados para ejercer el derecho en el Estado de Colorado. No podemos dar asesoría legal ni aceptar honorarios por asesoría legal. Solo ofrecemos servicios administrativos, de traducción y de notario público.",
        footer_copyright: "All Rights Reserved.",
        footer_disclaimer2: '"Quintana Notary & Signing" and "Ayuda DMV" are registered Trade Names of Servicios Quintana LLC.',
        lang_btn: "Español"
    },
    es: {
        nav_divisions: "Nuestras Marcas",
        nav_about: "Nosotros",
        nav_contact: "Contacto",
        hero_eyebrow: "Est. 2026 • Colorado",
        hero_h1: "Cerrando la Brecha Entre Comunidad y Cumplimiento.",
        hero_sub: "Servicios Quintana LLC es el hogar de Colorado para servicios bilingües confiables que hacen que los procesos oficiales, gubernamentales y digitales sean accesibles para todos. Reunimos tres marcas especializadas bajo una misión: ayudar a nuestra comunidad a navegar trámites, agencias y tecnología con claridad y confianza.",
        btn_view_companies: "Ver Nuestras Marcas",
        div_header: "Nuestras Marcas",
        div_sub: "Operamos tres marcas distintas que sirven al área metropolitana de Denver.",
        badge_auth: "Autenticación de Documentos",
        badge_admin: "Apoyo Administrativo",
        badge_digital: "Estrategia Digital y Desarrollo Web",
        badge_translation: "Servicios de Traducción",
        card_notary_title: "Quintana Notary & Signing",
        card_notary_text: "Servicios notariales móviles y bilingües para cierres de bienes raíces, declaraciones juradas, poderes y más. Llevamos la oficina a su puerta.",
        card_dmv_title: "Ayuda DMV",
        card_dmv_text: "Asistencia especializada para residentes hispanohablantes que navegan los requisitos del DMV de Colorado. Simplificamos los procesos estatales para que las familias puedan avanzar sin estrés.",
        card_dev_title: "David Quintana Dev",
        card_dev_text: "Arquitectura web bilingüe de alto rendimiento para negocios locales. Construimos sitios web accesibles y modernos con programación personalizada y diseño enfocado en la comunidad.",
        card_translation_title: "Servicios de Traducción Certificada",
        card_translation_text: "Traducciones certificadas profesionales para familias, estudiantes e individuos que completan trámites de inmigración, académicos o gubernamentales. Cada traducción incluye una Declaración de Exactitud firmada, diseñada para cumplir con los estrictos requisitos de presentación de USCIS, el DMV de Colorado, escuelas y agencias estatales.",
        card_translation_contact: "Más Información Sobre Servicios de Traducción",
        card_visit: "Visitar Sitio Oficial",
        card_portfolio: "Ver Portafolio",
        about_h2: "Construido Sobre Integridad",
        about_p1: "Servicios Quintana LLC reúne el trabajo profesional de David Quintana.",
        about_p2: "Ya sea que estemos notarizando un documento de préstamo en Castle Rock, ayudando a una familia a registrar un vehículo o escribiendo HTML semántico para un negocio local, nuestro valor fundamental sigue siendo el mismo: Accesibilidad.",
        about_p3: "Las barreras del idioma y la complejidad técnica nunca deben impedir que alguien alcance sus objetivos.",
        about_trust_h3: "Por Qué Colorado Confía en Nosotros",
        stat_brands: "Marcas Activas",
        stat_bilingual: "Bilingüe",
        stat_local: "Propiedad Local",
        footer_brand_tagline: "Confiable. Móvil. Bilingüe.",
        footer_hq: "Sede Corporativa y Agente Registrado",
        footer_contact_title: "Contacto",
        footer_statutory_en: "Important Notice: Servicios Quintana LLC and its representatives are not attorneys licensed to practice law in the State of Colorado. We may not give legal advice or accept fees for legal advice. We provide administrative, translation, and notary public services only.",
        footer_statutory_es: "Aviso Importante: Servicios Quintana LLC y sus representantes no son abogados licenciados para ejercer el derecho en el Estado de Colorado. No podemos dar asesoría legal ni aceptar honorarios por asesoría legal. Solo ofrecemos servicios administrativos, de traducción y de notario público.",
        footer_copyright: "Todos los Derechos Reservados.",
        footer_disclaimer2: '"Quintana Notary & Signing" y "Ayuda DMV" son Nombres Comerciales registrados de Servicios Quintana LLC.',
        lang_btn: "English"
    }
};

// ... (Keep the rest of your DOMContentLoaded event listeners and animations exactly as they were) ...
